param([Parameter(Mandatory = $true)][string]$FixturePath)

# Opt-in only. The fixture is generated by the Rust ignored test of the same name.
# Never use a production server, execute a real LLM, or print profile/pane contents.
$ErrorActionPreference = 'Stop'
$fixture = Get-Content -LiteralPath $FixturePath -Raw | ConvertFrom-Json
if ($fixture.server -notmatch '^svi_profile_smoke_[0-9a-f]{32}$' -or $fixture.session -ne 'svi_profile_smoke_codex_1') {
  throw 'Not an isolated tmux smoke fixture.'
}
$tmux = (Get-Command tmux -CommandType Application -ErrorAction Stop | Select-Object -First 1).Path
$ps = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
$server = $fixture.server
$target = '=' + $fixture.session
$created = $false

function Invoke-SmokeTmux([string[]]$Arguments) {
  $result = & $tmux -L $server @Arguments 2>&1 | Out-String
  if ($LASTEXITCODE -ne 0) { throw ('Isolated tmux operation failed: ' + $Arguments[0]) }
  return $result.Trim()
}

function Wait-SmokeMarker([string]$Pane, [string[]]$Markers) {
  for ($attempt = 0; $attempt -lt 80; $attempt++) {
    $text = Invoke-SmokeTmux @('capture-pane', '-p', '-t', $Pane, '-S', '-200')
    $missing = @($Markers | Where-Object { -not $text.Contains($_) })
    if ($missing.Count -eq 0) { return }
    Start-Sleep -Milliseconds 150
  }
  throw 'Isolated pane did not produce the expected profile/version/routing markers (contents withheld).'
}

try {
  # Refuse even a UUID collision rather than touching a preexisting test server.
  $ErrorActionPreference = 'Continue'
  $null = & $tmux -L $server has-session 2>&1
  $existed = $LASTEXITCODE -eq 0
  $ErrorActionPreference = 'Stop'
  if ($existed) { throw 'Test server already exists; generate a new fixture.' }
  $created = $true
  $encoded = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($fixture.prepareScript))
  $ErrorActionPreference = 'Continue'
  $prepareLog = & $ps -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -OutputFormat Text -EncodedCommand $encoded 2>&1 | Out-String
  $prepareExit = $LASTEXITCODE
  $ErrorActionPreference = 'Stop'
  if ($prepareExit -ne 82) {
    foreach ($line in ($prepareLog -split "`n")) {
      if ($line.Trim() -match '^SVI_CTRL_[a-z-]+_EXIT=[0-9-]+_OK=(?:True|False)$') { Write-Host $line.Trim() }
    }
    Write-Host ('Control diagnostic length: ' + $prepareLog.Length)
    foreach ($kind in @('invalid option', 'unknown option', 'no value', 'usage:', 'bad value', 'too many', 'not a valid', 'no server', 'ambiguous', 'command not found', 'default-shell', 'default-command', 'destroy-unattached', 'remain-on-exit', 'syntax', 'error connecting', 'session not found', "can't find", 'not found', 'target', 'option', 'shell', 'bad', 'value', 'argument', 'index')) {
      if ($prepareLog.Contains($kind)) { Write-Host "Control diagnostic category: $kind" }
    }
    throw "Isolated production prepare failed (exit $prepareExit; raw diagnostics withheld)."
  }
  $globalShell = Invoke-SmokeTmux @('show-options', '-g', '-v', 'default-shell')
  $globalIsPs51 = $globalShell.Trim('"').Replace('/', '\') -ieq $ps
  Write-Host "Isolated server inherited global PS5.1 default-shell: $globalIsPs51 (user configuration was not bypassed)."
  $shell = Invoke-SmokeTmux @('show-options', '-v', '-t', ($target + ':'), 'default-shell')
  $command = Invoke-SmokeTmux @('show-options', '-v', '-t', ($target + ':'), 'default-command')
  if ($shell -ne $ps -or $command -ne '') { throw 'New session did not receive PS5.1 / empty default-command.' }
  $initial = Invoke-SmokeTmux @('display-message', '-p', '-t', ($target + ':'), '#{pane_id}')
  Wait-SmokeMarker $initial @('SVI_PS_VERSION=5.1', 'SVI_PROFILE_TYPE=Function', 'SVI_FUNCTION_ROUTED')
  Write-Host 'PASS production new-session: PS5.1, profile Codex function, harmless name-based routing.'

  $null = Invoke-SmokeTmux @('set-option', '-t', ($target + ':'), 'default-command', 'svi_test_preserve_existing')
  $null = & $ps -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -OutputFormat Text -EncodedCommand $encoded 2>&1
  if ($LASTEXITCODE -ne 81) { throw 'Existing test session was not reused.' }
  $unchanged = Invoke-SmokeTmux @('show-options', '-v', '-t', ($target + ':'), 'default-command')
  if ($unchanged -ne 'svi_test_preserve_existing') { throw 'Prepare modified an existing session option.' }
  $null = Invoke-SmokeTmux @('set-option', '-F', '-t', ($target + ':'), 'default-command', '#{l:}')
  Write-Host 'PASS existing-session preparation preserves its shell settings.'

  $window = Invoke-SmokeTmux @('new-window', '-d', '-P', '-F', '#{pane_id}', '-t', $target, '-n', 'interactive-probe')
  $split = Invoke-SmokeTmux @('split-window', '-d', '-P', '-F', '#{pane_id}', '-t', $window)
  foreach ($pane in @($window, $split)) {
    if ($pane -notmatch '^%[0-9]+$') { throw 'Invalid isolated pane target.' }
    # Fragment the marker in the input so an echoed command cannot pass the check.
    $probe = "Write-Output ('SVI_INTERACTIVE_' + 'PS=' + `$PSVersionTable.PSVersion.Major + '.' + `$PSVersionTable.PSVersion.Minor); Write-Output ('SVI_INTERACTIVE_' + 'CODEX=' + (Get-Command codex).CommandType)"
    $null = Invoke-SmokeTmux @('send-keys', '-t', $pane, '-l', $probe)
    $null = Invoke-SmokeTmux @('send-keys', '-t', $pane, 'Enter')
    Wait-SmokeMarker $pane @('SVI_INTERACTIVE_PS=5.1', 'SVI_INTERACTIVE_CODEX=Function')
  }
  Write-Host 'PASS new-window and split-window: inherited interactive PS5.1 with profiles.'
} finally {
  if ($created) {
    $ErrorActionPreference = 'Continue'
    $null = & $tmux -L $server kill-server 2>&1
    Write-Host 'Isolated test server cleaned up; production servers/sessions were not changed.'
  }
}
